<program> ::= <filter> <order> | <filter> | <order> | <order> <filter> | E

<filter> ::= "filter" ":" <expression>  ";"

<order> ::= "order" ":" <id_list> ";"

<id_list> ::= <id> | <id> "," <id_list>

<binary_expression> ::= <unary_expression>
                      | <binary_expression>  "<"   <binary_expression>
                      | <binary_expression>  "<="  <binary_expression>
                      | <binary_expression>  ">"   <binary_expression>
                      | <binary_expression>  ">="  <binary_expression>
                      | <binary_expression>  "="  <binary_expression>
                      | <binary_expression>  "!="  <binary_expression>
                      | <binary_expression>  "and" <binary_expression>
                      | <binary_expression>  "or"  <binary_expression>

<unary_expression> ::= <primary_expression> |  <unary_operator> <unary_expression>

<unary_operator> ::= "+" | "-" | "not"

<primary_expression> ::= <id> | <number> | "(" <expression> ")"

<expression> ::= <binary_expression> | E


<id> ::= [a-z]+
<number> ::= <int> | <real>
<int> ::= "0" | [1-9] [0-9]*
<real> ::= ("0" |  [1-9] [0-9]*) ("." [0-9]+ )?