<program> ::= <filter> <order> | <filter> | <order> | <order> <filter> | E

<filter> ::= "filter" ":" <expression>  ";"

<order> ::= "order" ":" <id_list> ";"

<id_list> ::= <id> | <id> "," <id_list>

<expression> ::= <unary_expression>
                      | <expression>  "<"   <expression>
                      | <expression>  "<="  <expression>
                      | <expression>  ">"   <expression>
                      | <expression>  ">="  <expression>
                      | <expression>  "="  <expression>
                      | <expression>  "!="  <expression>
                      | <expression>  "and" <expression>
                      | <expression>  "or"  <expression>


<unary_expression> ::= <primary_expression> |  <unary_operator> <unary_expression>

<unary_operator> ::= "+" | "-" | "not"

<primary_expression> ::= <id> | <number> | "(" <expression> ")"


<id> ::= [a-z]+
<number> ::= <int> | <real>
<int> ::= "0" | [1-9] [0-9]*
<real> ::= ("0" |  [1-9] [0-9]*) ("." [0-9]+ )?